# Site settings
title: Benjamin Granados
description: Personal website and portfolio | Software Developer | Banco Santander
author: Benjamin Granados
email: benjamin.granadosm@gmail.com

baseurl: "/benjagm-page" # GitHub repository name
url: "https://benjagm.github.io" # GitHub username

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "benjagranados"
stackoverflow: "#"
github: "benjagm"
researchgate: "#"
orcid: "#"
quora: "#"
instagram: "#"
facebook: "#"
bluesky: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker (add your analytics ID if needed)
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - temp-gradfolio

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-sitemap
