# Site settings
title: Benjamin Granados
description: Personal website
author: Benjamin Granados
email: benjamin.granadosm@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
