# Site settings
title: Benjamin Granados
description: API & Community Leader | CDO | MBA | alum @ Postman, Twilio, BBVA & Celonis
author: Benjamin Granados
email: benjamin.granadosm@gmail.com

baseurl: "/benjagm-page" # GitHub repository name
url: "https://benjagm.github.io" # GitHub username

# Pagination (removed blog functionality)

# Social media links in footer
linkedin: "benjagranados"
github: "benjagm"
bluesky: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker (add your analytics ID if needed)
analytics:

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

# Collections (removed projects collection)

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE
  - .gitignore
  - temp-gradfolio

plugins:
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-feed
  - jekyll-sitemap
